/*
 * generated by Xtext 2.22.0
 */
package ac.soton.xumlb.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class XUmlbUiModule extends AbstractXUmlbUiModule {

	public XUmlbUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
