/*
 * generated by Xtext 2.22.0
 */
package ac.soton.xumlb;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class XUmlbStandaloneSetup extends XUmlbStandaloneSetupGenerated {

	public static void doSetup() {
		new XUmlbStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
