/*
 * generated by Xtext 2.22.0
 */
package ac.soton.xumlb.ui.tests;

import ac.soton.xumlb.ui.internal.XumlbActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class XUmlbUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XumlbActivator.getInstance().getInjector("ac.soton.xumlb.XUmlb");
	}

}
