/*
 * generated by Xtext 2.22.0
 */
package ac.soton.xumlb.parser.antlr;

import ac.soton.xumlb.parser.antlr.internal.InternalXUmlbParser;
import ac.soton.xumlb.services.XUmlbGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class XUmlbParser extends AbstractAntlrParser {

	@Inject
	private XUmlbGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalXUmlbParser createParser(XtextTokenStream stream) {
		return new InternalXUmlbParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "XUMLB";
	}

	public XUmlbGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(XUmlbGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
